### ISSUE TITLE
Make the module capable of handling multi language sites

### ISSUE THREAD

**Issue by trouble2** [40fingers/DNN-SEORedirect#95]
The documentation says there is an issue with multi-language sites;
"
When the site is a multiple languages site:
The 404 page cannot be a translated page in combination with an “generated” language URL.
When you want to translate your 404 message there are two options.
A. Make the 404 page a neutral language page and use a module that supports ML for your
message.
B. Make sure you have a unique portal-alias per language. 
"

I'm sure it is possible to think of a better solution

**Comment by Timo-Breumelhof** [comment]
The module can handle ML pages, you just have to use a translatable module like Open Content.
Due to the same reason mentioned here: https://github.com/40fingers/DNN-SEORedirect/issues/94 we believe there is no simple other solution. (we did think about it, but didn't find one)
If you have any suggestions for a solution, please let us know.
